# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-22 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0004_auto_20170921_2008'),
        ('pacientes', '0016_paciente_domicilio'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('hora', models.DateTimeField(auto_now=True)),
                ('motivo_consulta', models.TextField(blank=True, max_length=9200, null=True)),
                ('antecedentes_enfermedad', models.TextField(blank=True, max_length=9200, null=True)),
                ('diagnostico', models.TextField(blank=True, max_length=9200, null=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleados.Empleado')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente')),
            ],
            options={
                'verbose_name_plural': 'Historias Clínicas',
                'verbose_name': 'Historia Clínica',
            },
        ),
    ]
