# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-25 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleado_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='categoria',
            field=models.CharField(blank=True, choices=[('medico', 'Médico'), ('secretariado', 'Secretariado')], max_length=800, null=True),
        ),
    ]
