# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-25 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20170719_0532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='foto',
            new_name='file',
        ),
    ]
