# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-25 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_auto_20170725_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='paciente',
        ),
        migrations.AddField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_pacientes'),
        ),
    ]
