# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-24 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_auto_20170724_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='telefono',
            new_name='telefono_celular',
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
