# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-25 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_empleado_categoria'),
        ('pacientes', '0008_paciente_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='empleado',
            field=models.ManyToManyField(blank=True, to='empleados.Empleado'),
        ),
    ]
