# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-18 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_paciente_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='portadas_libros'),
        ),
    ]
