# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-21 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0013_auto_20170921_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='empleado',
        ),
    ]
