# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-21 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0014_remove_paciente_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='edad',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
