# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-22 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0015_paciente_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='domicilio',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
