# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-10 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0016_paciente_domicilio'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='numero_afiliado',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
