# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-26 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_turno_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='motivo',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
