# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-21 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_empleado_categoria'),
        ('turnos', '0004_auto_20170726_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.AddField(
            model_name='turno',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleados.Empleado'),
        ),
    ]
