# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-22 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_auto_20170921_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='fecha',
            field=models.DateField(auto_now=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turno',
            name='hora',
            field=models.DateTimeField(auto_now=True, null=True),
            preserve_default=False,
        ),
    ]
