# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-25 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
